### ISSUE TITLE
Version 0 makes sisyphus/elx uninstallable

### ISSUE THREAD

**Issue by meedstrom** [tarsius/llama#2]
At least when I use Elpaca (`M-x elpaca-try RET sisyphus RET`), it'll download the packages but won't load them because elx requires llama "0.3.0" but llama is at "0".

**Comment by meedstrom** [comment]
Interesting fix! I would like to remove the version header in my code too (I don't publish to [Non]GNU ELPA). 

Do you know anywhere the implications are discussed? Maybe it's been talked about in a Melpa issue, but searching `is-issue "Package-Version:"` returns [250 issues](https://github.com/melpa/melpa/issues?q=%22Package-Version%3A%22+is%3Aissue+).  I know you have talked a lot about version strings in https://github.com/melpa/melpa/issues/2955 but I don't think I saw this.

I guess mainly I'm worried that when MELPA rolls out the new numbering scheme, it would walk the commit history and see a higher version string in the past and publish that on Stable.  I could fix it by tagging an even higher version, I suppose.

Btw, the Elisp manual says a version must be present - I guess that's why you intend to add back a version 0?

```
The version number comes from the ‘Package-Version’ header, if it
exists, or from the ‘Version’ header otherwise.  One or the other _must_
be present.
```

**Comment by tarsius** [comment]
I have tried to explain many times, why it is a bad idea to use embedded version strings are bad idea, when we have tags, which actually unambiguously identify releases. Very briefly, every commit starting with release N and up to the next release, will claim to actually be N. (But I don't want to go dig that up for you now.)

Unfortunately I was never able to convince anyone and have recently given up. That's why I have added the header to all my packages now. Convincing people otherwise is a lost cause. For consistency I have done it for all packages, even those not on [Non]GNU Elpa. All the other packages already had this header, or were ready for a release (so I could add the header in the release commit (which obviously is the only correct commit to add (or bump) this header)).

> I guess mainly I'm worried that when MELPA rolls out the new numbering scheme, it would walk the commit history and see a higher version string in the past and publish that on Stable.

I very much hope that I can at least convince the other Melpa maintainers that in the presence of release tags, those should be used as the only source of truth and that history walking to find the first commit that claims to be a release, should only be used in their absence.

**Comment by meedstrom** [comment]
Yea, I get the problem with embedded strings, and I agree git tags work best. I've just never seen a package embedding version "0" or even missing a version header - I didn't know it was legal to leave it out. Makes me oddly happy.

**Comment by meedstrom** [comment]
Hi again, it was a while because I waited for package recipes to update and all that.  Not sure if you know what's going on here, but I still get 

    llama installed version (0) lower than min required 0.3.1

when I attempt to install Sisyphus.

I've verified that my installed llama.el is the new version with no version header, by visiting the source file with `M-x find-library RET llama RET` and seeing the absence of such a comment.

I've also had my Elpaca has refresh its Melpa recipes, with `M-x elpaca-update-menus RET elpaca-menu-melpa RET`.

Does the absence of a Version: get interpreted as version 0?  It does indeed seem that way: the message is coming from elpaca--check-version where it seems to fall back on "0" on not finding a declared version https://github.com/progfolio/elpaca/blob/c6395a6c8f85b09e8a0dddb0d800b024323af9b3/elpaca.el#L1247

**Comment by tarsius** [comment]
Yes, it seems like Elpaca cannot handle the absence of the header in this case either.

I've just started working on `llama` again and plan to release in about a week. So I recommend you just wait until then. Alternatively you could clone this repository, add the header, and point Elpaca at your clone. (I believe involves something like `(elpaca (example :host gitlab :repo "user/example" :inherit nil))`. I would be surprised if you couldn't instead point it at a local repository.)

**Comment by progfolio** [comment]
> Yes, it seems like Elpaca cannot handle the absence of the header in this case either.

Not the case. The package recipe just needs to be altered. See: https://github.com/progfolio/elpaca/issues/353#issuecomment-2352633015

**Comment by meedstrom** [comment]
@tarsius Installation works now, FYI! Don't feel stressed to release :)
