### ISSUE TITLE
how can one create interactive lambda commands with `##` ?

### ISSUE THREAD

**Issue by suhail-singh** [tarsius/llama#3]
In some situations, one needs to create a wrapper command that can be bound to a
key-binding.  The name of the function isn't necessary, and so a lambda with an
interactive form suffices.  How would one use `##` to create an interactive
`lambda`?

**Comment by tarsius** [comment]
That is not currently possible and I think it would probably be a bad idea.

Assuming you wanted to avoid having to write

```elisp
(λ (arg) (interactive "p") (message "prefix: %s" arg))
```

you probably tried something like

```elisp
(## (interactive "p") (message "prefix: %s" %))
```

which doesn't work and cannot even be macro-expanded, because

```elisp
(## (interactive "p") (message "prefix: %s" %))
   `-- fbound symbol is expected here
```

in desperation you might have tried

```elisp
(##anon (interactive "p") (message "prefix: %s" %))
```

which expands to

```elisp
(lambda
  (%)
  (anon
   (interactive "p")
   (message "prefix: %s" %)))
```

which obviously isn't what we want.

The documentation says

> The `##` macro, whose signature is `(## FN &rest BODY)`, expands to a `lambda` expression, which wraps around these arguments.

I.e., it has the form `(lambda` + generated argument list + BODY as-is + `)`.

It could be expanded to support an alternative, completely different, form `(fn (interactive ARGS...) BODY...)`. Note that BODY would not begin with FN. There would have to be at least one `(...)` in there -- like in the initial code block above.

I fear that would make it harder for users to understand how it works. It would also give those more ammunition who think that the whole idea of this macro is sacrilegious idea to begin with.

So I don't think I will do this. I might eventually implement it, just to do some experiments, but my current feeling is that adding this feature would be a bad idea.

**Comment by tarsius** [comment]
To me not requiring an extra pair of parens is an important feature. If you prefer the extra parens, then https://github.com/troyp/fn.el might be for you.

**Comment by linwaytin** [comment]
Sorry for replying to this closed issue, but I have the same need. 

At least for simple cases, I think a solution is creating the lambda using
```elisp
(##interactive (org-tree-to-indirect-buffer t))
```
which can be bound to a key.

**Comment by meedstrom** [comment]
If I may offer my experience, I used to have a macro for that, reproduced below but it was based on Tarsius' previous l.el package.

But @linwaytin, I didn't end up using it nearly as much as I thought. For your example it'd have looked like e.g.:

```elisp
(global-set-key (kbd "C-x C-k") (c'org-tree-to-indirect-buffer t))
```

but I used it what? Twice?  If you want less visual noise in initfiles, it's worth just defining those commands as defuns in a separate lib.el and forgetting about them. 

```elisp
(defmacro c (fn &rest body)
  "Interactive version of `l' (short anonymous lambda).
FN and BODY as in `l'.  A typical use-case is with `keymap-set'
to make a simple command on the fly without the expression
flowing across two lines."
  (require 'l)
  `(lambda ,(l--arguments body)
     (interactive)
     (,(if (car-safe fn)
           (cadr fn)
         fn)
      ,@body)))
```

**Comment by linwaytin** [comment]
Thanks for sharing!
